In [1]:
import pandas as pd

corr_diff = pd.read_csv('Evaluation_Results/corr_diff.csv')
corr_diff_wide = corr_diff.pivot(index='Dataset', columns='Model', values='Pairwise Corr Diff')
avg_row = corr_diff_wide.mean(axis=0)
corr_diff_wide.loc['Average'] = avg_row
corr_diff_wide = corr_diff_wide.round(3)
corr_diff_wide.to_csv('Final_Results/corr_diff_wide.csv')
corr_diff_wide

Model    copula_gan  ctgan     ds  gaussian_copula  synthpop   tvae
Dataset
1             0.149  0.148  0.155            0.099     0.031  0.129
2             0.046  0.047  0.048            0.035     0.023  0.172
3             0.237  0.239  0.252            0.190     0.094  0.114
5             0.082  0.081  0.120            0.073     0.042  0.093
6             0.044  0.028  0.037            0.038     0.013  0.023
Average       0.112  0.109  0.122            0.087     0.041  0.106

In [2]:
jsd = pd.read_csv('Evaluation_Results/jsd.csv')
jsd_wide = jsd.pivot(index='Dataset', columns='Model', values='JSD Diff')
avg_row = jsd_wide.mean(axis=0)
jsd_wide.loc['Average'] = avg_row
jsd_wide = jsd_wide.round(3)
jsd_wide.to_csv('Final_Results/jsd_wide.csv')
jsd_wide

Model    copula_gan  ctgan     ds  gaussian_copula  synthpop   tvae
Dataset
1             0.040  0.050  0.086            0.035     0.001  0.138
2             0.002  0.027  0.020            0.000     0.000  0.071
3             0.167  0.144  0.196            0.170     0.001  0.168
5             0.011  0.012  0.090            0.004     0.000  0.146
6             0.079  0.066  0.115            0.107     0.034  0.080
Average       0.060  0.060  0.101            0.063     0.007  0.121

In [3]:
wd = pd.read_csv('Evaluation_Results/wd.csv')
wd_wide = wd.pivot(index='Dataset', columns='Model', values='WD Diff')
avg_row = wd_wide.mean(axis=0)
wd_wide.loc['Average'] = avg_row
wd_wide = wd_wide.round(3)
wd_wide.to_csv('Final_Results/wd_wide.csv')
wd_wide

Model    copula_gan  ctgan     ds  gaussian_copula  synthpop   tvae
Dataset
1             0.019  0.028  0.057            0.012     0.004  0.111
2             0.024  0.020  0.073            0.008     0.003  0.132
3             0.031  0.029  0.096            0.024     0.008  0.067
5             0.050  0.046  0.139            0.010     0.007  0.234
6             0.031  0.026  0.016            0.006     0.006  0.030
Average       0.031  0.030  0.076            0.012     0.006  0.115

In [4]:
dcr = pd.read_csv('Evaluation_Results/dcr.csv')
dcr_wide = dcr.pivot(index='Dataset', columns='Model', values=['DCR 5th Percentile', 'DCR 5th Percentile (within Real)', 'DCR 5th Percentile (within Synthetic)'])
avg_row = dcr_wide.mean(axis=0)
dcr_wide.loc['Average'] = avg_row
dcr_wide = dcr_wide.round(3)
dcr_wide.to_csv('Final_Results/dcr_wide.csv')
dcr_wide

        DCR 5th Percentile                                                  \
Model           copula_gan   ctgan      ds gaussian_copula synthpop   tvae
Dataset
1                   10.536  12.083  11.619           8.544    5.099  7.071
2                    0.000   0.000   0.000           0.000    0.000  0.000
3                   11.650  11.135  40.934           9.420    5.095  7.119
5                    3.464   3.464   4.899           3.317    2.828  3.317
6                    6.708   6.164  10.293          13.075    2.449  5.916
Average              6.472   6.569  13.549           6.871    3.094  4.685

        DCR 5th Percentile (within Real)                                \
Model                         copula_gan  ctgan     ds gaussian_copula
Dataset
1                                  4.873  4.873  4.873           4.873
2                                  0.000  0.000  0.000           0.000
3                                  6.009  6.009  6.009           6.009
5                                  3.000  3.000  3.000           3.000
6                                  2.236  2.236  2.236           2.236
Average                            3.224  3.224  3.224           3.224

                        DCR 5th Percentile (within Synthetic)                 \
Model   synthpop   tvae                            copula_gan  ctgan      ds
Dataset
1          4.873  4.873                                 5.099  4.796   5.477
2          0.000  0.000                                 0.000  0.000   0.000
3          6.009  6.009                                 5.490  5.853   9.704
5          3.000  3.000                                 3.000  2.828   2.449
6          2.236  2.236                                10.812  9.157  15.492
Average    3.224  3.224                                 4.880  4.527   6.624


Model   gaussian_copula synthpop   tvae
Dataset
1                 5.000    2.000  3.317
2                 0.000    0.000  0.000
3                 5.478    1.734  3.283
5                 2.646    2.000  0.000
6                22.627    5.099  8.000
Average           7.150    2.167  2.920

In [5]:
nndr = pd.read_csv('Evaluation_Results/nndr.csv')
nndr_wide = nndr.pivot(index='Dataset', columns='Model', values=['NNDR 5th percentile', 'NNDR 5th percentile (within Real)', 'NNDR 5th percentile (within Synthetic)'])
avg_row = nndr_wide.mean(axis=0)
nndr_wide.loc['Average'] = avg_row
nndr_wide = nndr_wide.round(3)
nndr_wide.to_csv('Final_Results/nndr_wide.csv')
nndr_wide

        NNDR 5th percentile                                                \
Model            copula_gan  ctgan     ds gaussian_copula synthpop   tvae
Dataset
1                     0.569  0.569  0.591           0.562    0.464  0.590
2                     0.000  0.000  0.000           0.000    0.000  0.000
3                     0.536  0.622  0.543           0.533    0.334  0.534
5                     0.761  0.768  0.419           0.791    0.750  0.832
6                     0.196  0.174  0.212           0.132    0.045  0.203
Average               0.412  0.427  0.353           0.404    0.319  0.432

        NNDR 5th percentile (within Real)                                \
Model                          copula_gan  ctgan     ds gaussian_copula
Dataset
1                                   0.438  0.438  0.438           0.438
2                                   0.000  0.000  0.000           0.000
3                                   0.583  0.583  0.583           0.583
5                                   0.775  0.775  0.775           0.775
6                                   0.073  0.073  0.073           0.073
Average                             0.374  0.374  0.374           0.374

                        NNDR 5th percentile (within Synthetic)                \
Model   synthpop   tvae                             copula_gan  ctgan     ds
Dataset
1          0.438  0.438                                  0.632  0.632  0.566
2          0.000  0.000                                  0.000  0.000  0.000
3          0.583  0.583                                  0.666  0.691  0.546
5          0.775  0.775                                  0.834  0.832  0.707
6          0.073  0.073                                  0.143  0.131  0.151
Average    0.374  0.374                                  0.455  0.457  0.394


Model   gaussian_copula synthpop   tvae
Dataset
1                 0.612    0.357  0.586
2                 0.000    0.000  0.000
3                 0.694    0.472  0.647
5                 0.832    0.745  0.000
6                 0.114    0.065  0.114
Average           0.450    0.328  0.269

In [6]:
rf = pd.read_csv('Evaluation_Results/RF_Results.csv')
rf_wide = rf.pivot(index="Dataset", columns="Model", values=["Accuracy Difference", "F1 Score Difference", "ROC AUC Difference"])
avg_row = rf_wide.mean(axis=0)
rf_wide.loc['Average'] = avg_row
rf_wide.to_csv('Final_Results/rf_wide.csv')
rf_wide

        Accuracy Difference                                               \
Model            copula_gan ctgan     ds gaussian_copula synthpop   tvae
Dataset
1                      0.42  0.50  0.460            0.37    0.070  0.190
2                     -0.07  0.43  0.040           -0.06   -0.040 -0.030
3                      0.00  0.00  0.330            0.00   -0.090 -0.040
5                      0.18  0.24  0.140            0.04    0.030  0.000
6                      0.02  0.03  0.020            0.05    0.020  0.040
Average                0.11  0.24  0.198            0.08   -0.002  0.032

        F1 Score Difference                                               \
Model            copula_gan  ctgan     ds gaussian_copula synthpop  tvae
Dataset
1                     0.440  0.550  0.470           0.420    0.070  0.24
2                     0.010  0.500  0.050           0.010    0.010 -0.02
3                     0.050  0.050  0.250           0.050   -0.100 -0.04
5                     0.150  0.190  0.140           0.120    0.110  0.04
6                     0.060  0.020  0.030           0.090    0.020  0.03
Average               0.142  0.262  0.188           0.138    0.022  0.05

        ROC AUC Difference
Model           copula_gan ctgan     ds gaussian_copula synthpop   tvae
Dataset
1                    0.400  0.43  0.490           0.400    0.050  0.100
2                    0.060  0.02  0.040          -0.040   -0.050 -0.030
3                    0.050 -0.03  0.340           0.040   -0.030  0.070
5                    0.210  0.21  0.140           0.100   -0.020  0.050
6                    0.040  0.02  0.060           0.120    0.030  0.040
Average              0.152  0.13  0.214           0.124   -0.004  0.046

In [7]:
lr = pd.read_csv('Evaluation_Results/LR_Results.csv')
lr_wide = lr.pivot(index="Dataset", columns="Model", values=["Accuracy Difference", "F1 Score Difference", "ROC AUC Difference"])
avg_row = lr_wide.mean(axis=0)
lr_wide.loc['Average'] = avg_row
lr_wide.to_csv('Final_Results/lr_wide.csv')
lr_wide

        Accuracy Difference                                                \
Model            copula_gan  ctgan     ds gaussian_copula synthpop   tvae
Dataset
1                     0.300  0.360  0.360           0.360     0.04  0.200
2                    -0.010  0.500 -0.010          -0.010     0.00  0.010
3                    -0.080 -0.080  0.290          -0.080    -0.08 -0.170
5                     0.100  0.230  0.120           0.080     0.09  0.090
6                     0.010  0.030  0.010           0.030     0.00  0.010
Average               0.064  0.208  0.154           0.076     0.01  0.028

        F1 Score Difference                                               \
Model            copula_gan  ctgan    ds gaussian_copula synthpop   tvae
Dataset
1                     0.460  0.470  0.41            0.44     0.05  0.230
2                     0.000  0.500  0.00            0.00     0.00 -0.050
3                     0.000  0.000  0.26            0.00    -0.08 -0.150
5                     0.180  0.210  0.15            0.19     0.17  0.110
6                     0.020 -0.010  0.03            0.12     0.01  0.030
Average               0.132  0.234  0.17            0.15     0.03  0.034

        ROC AUC Difference
Model           copula_gan ctgan     ds gaussian_copula synthpop  tvae
Dataset
1                    0.380  0.53  0.350           0.350    0.000  0.17
2                    0.130  0.19  0.170           0.010    0.010  0.01
3                    0.100 -0.17  0.060           0.020   -0.050 -0.17
5                    0.160  0.25  0.190           0.100    0.040  0.03
6                    0.000  0.00  0.060           0.050   -0.010  0.01
Average              0.154  0.16  0.166           0.106   -0.002  0.01

In [8]:
mlp = pd.read_csv('Evaluation_Results/MLP_Results.csv')
mlp_wide = mlp.pivot(index="Dataset", columns="Model", values=["Accuracy Difference", "F1 Score Difference", "ROC AUC Difference"])
avg_row = mlp_wide.mean(axis=0)
mlp_wide.loc['Average'] = avg_row
mlp_wide.to_csv('Final_Results/mlp_wide.csv')
mlp_wide

        Accuracy Difference                                                \
Model            copula_gan  ctgan     ds gaussian_copula synthpop   tvae
Dataset
1                     0.280  0.380  0.330           0.310   -0.030  0.050
2                    -0.020  0.490  0.010          -0.020   -0.010  0.010
3                     0.000  0.000  0.370           0.000    0.000 -0.040
5                     0.090  0.250  0.250           0.070    0.020  0.050
6                    -0.080  0.070 -0.080           0.000    0.000  0.000
Average               0.054  0.238  0.176           0.072   -0.004  0.014

        F1 Score Difference                                               \
Model            copula_gan ctgan     ds gaussian_copula synthpop   tvae
Dataset
1                     0.340  0.44  0.370           0.390   -0.010  0.110
2                     0.000  0.50  0.010           0.000   -0.010 -0.030
3                     0.000  0.00  0.240          -0.050   -0.080 -0.090
5                     0.050  0.20  0.180           0.130    0.010  0.070
6                    -0.100  0.06 -0.070           0.000    0.000  0.000
Average               0.058  0.24  0.146           0.094   -0.018  0.012

        ROC AUC Difference
Model           copula_gan  ctgan     ds gaussian_copula synthpop   tvae
Dataset
1                     0.39  0.400  0.280           0.460    0.000  0.120
2                     0.11  0.130  0.120          -0.010    0.000 -0.010
3                    -0.14 -0.110 -0.110          -0.170   -0.200 -0.110
5                     0.10  0.180  0.190           0.130    0.030  0.050
6                    -0.01  0.010  0.010           0.010    0.010  0.010
Average               0.09  0.122  0.098           0.084   -0.032  0.012

In [12]:
# Save plots also in Final_Results
import shutil
import os

# Define the source and destination directories
source_dir = 'Evaluation_Results/Plots'
destination_dir = 'Final_Results/Plots'

# Remove the destination directory if it exists
if os.path.exists(destination_dir):
    shutil.rmtree(destination_dir)

# Copy all files from source to destination
shutil.copytree(source_dir, destination_dir)

FileExistsError: [Errno 17] File exists: 'Final_Results/Plots'